### ISSUE TITLE
Struggling to install lalsuite on conda

### ISSUE THREAD

**Issue by Jedop** [conda-forge/lalsuite-feedstock#49]
### Comment:

I'm very new to using conda and stuff, and when i try to install lalsuite i get this

I apologize in advance if my problem is a result of some amateur mistake

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides lal >=6.20.1 needed by lalsuite-6.57-py_1

Could not solve for environment specs
The following packages are incompatible
└─ lalsuite is not installable because there are no viable options
   ├─ lalsuite 6.57 would require
   │  └─ lal >=6.20.1 , which does not exist (perhaps a missing channel);
   ├─ lalsuite 6.60 would require
   │  └─ lal 6.20.2.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite [6.63|6.64|...|6.69] would require
   │  └─ lal 6.21.0.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 6.70 would require
   │  └─ lal 6.22.0.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite [6.71|6.72|...|6.78] would require
   │  └─ lal 7.0.0.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite [6.79|6.80] would require
   │  └─ lal 7.1.0.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 6.81 would require
   │  └─ lal 7.1.1.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 6.82 would require
   │  └─ lal 7.1.2.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.0 would require
   │  └─ lal 7.1.3.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.1 would require
   │  └─ lal 7.1.4.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite [7.10|7.11] would require
   │  └─ lal 7.2.4.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.2 would require
   │  └─ lal 7.1.5.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.3 would require
   │  └─ lal 7.1.6.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite [7.4|7.5] would require
   │  └─ lal 7.1.7.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.6 would require
   │  └─ lal 7.2.0.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.8 would require
   │  └─ lal 7.2.2.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.13 would require
   │  └─ lal 7.3.0.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite [7.14|7.15|7.19] would require
   │  └─ lal 7.3.1.* , which does not exist (perhaps a missing channel);
   ├─ lalsuite 7.21 would require
   │  └─ lal 7.4.1.* , which does not exist (perhaps a missing channel);
   └─ lalsuite 7.22 would require
      └─ lal 7.5.0.* , which does not exist (perhaps a missing channel).
![Screenshot (554)](https://github.com/conda-forge/lalsuite-feedstock/assets/154212178/99f18bf0-fa14-40a4-8a77-955b580ac553)

**Comment by duncanmmacleod** [comment]
@jedop, it looks like you're trying to install LALSuite on Windows. LALSuite is not available on that platform.

There is a very old 'noarch' (platform independent) `lalsuite` package that your conda is _trying_ to install, but it can't find any of the actual compiled libraries (since they have never been available).

On Windows I strongly recommend trying out the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/), which provides a native Linux system on Windows (it's excellent, IMO), in which you can install lalsuite with conda.

**Comment by Jedop** [comment]
Thank you for your response. I actually ended up figuring that out yesterday late night, and it worked out fine(although there were other weird errors but I was able to find solutions online). Thanks!
